/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/_wallet'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedWalletAccountsRouteImport } from './routes/_authenticated/_wallet/accounts'
import { Route as AuthenticatedWalletDashboardRouteImport } from './routes/_authenticated/_wallet/dashboard'
import { Route as AuthenticatedWalletTransactionsRouteImport } from './routes/_authenticated/_wallet/transactions'
import { Route as AuthenticatedWalletAccountsIndexRouteImport } from './routes/_authenticated/_wallet/accounts/index'
import { Route as AuthenticatedWalletAccountsAccountIdRouteImport } from './routes/_authenticated/_wallet/accounts/$accountId'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/_wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedWalletAccountsRoute =
  AuthenticatedWalletAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletDashboardRoute =
  AuthenticatedWalletDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletTransactionsRoute =
  AuthenticatedWalletTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletAccountsIndexRoute =
  AuthenticatedWalletAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWalletAccountsRoute,
  } as any)
const AuthenticatedWalletAccountsAccountIdRoute =
  AuthenticatedWalletAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedWalletAccountsRoute,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/accounts': typeof AuthenticatedWalletAccountsRouteWithChildren
  '/dashboard': typeof AuthenticatedWalletDashboardRoute
  '/transactions': typeof AuthenticatedWalletTransactionsRoute
  '/accounts/$accountId': typeof AuthenticatedWalletAccountsAccountIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/accounts/': typeof AuthenticatedWalletAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/dashboard': typeof AuthenticatedWalletDashboardRoute
  '/transactions': typeof AuthenticatedWalletTransactionsRoute
  '/accounts/$accountId': typeof AuthenticatedWalletAccountsAccountIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/accounts': typeof AuthenticatedWalletAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_wallet': typeof AuthenticatedWalletRouteWithChildren
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_wallet/accounts': typeof AuthenticatedWalletAccountsRouteWithChildren
  '/_authenticated/_wallet/dashboard': typeof AuthenticatedWalletDashboardRoute
  '/_authenticated/_wallet/transactions': typeof AuthenticatedWalletTransactionsRoute
  '/_authenticated/_wallet/accounts/$accountId': typeof AuthenticatedWalletAccountsAccountIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/_authenticated/_wallet/accounts/': typeof AuthenticatedWalletAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/accounts'
    | '/dashboard'
    | '/transactions'
    | '/accounts/$accountId'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/dashboard'
    | '/transactions'
    | '/accounts/$accountId'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/_admin'
    | '/_authenticated/_wallet'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_wallet/accounts'
    | '/_authenticated/_wallet/dashboard'
    | '/_authenticated/_wallet/transactions'
    | '/_authenticated/_wallet/accounts/$accountId'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/_authenticated/_wallet/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_wallet': {
      id: '/_authenticated/_wallet'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_wallet/accounts': {
      id: '/_authenticated/_wallet/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedWalletAccountsRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/_wallet/dashboard': {
      id: '/_authenticated/_wallet/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedWalletDashboardRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/_wallet/transactions': {
      id: '/_authenticated/_wallet/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedWalletTransactionsRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/_wallet/accounts/': {
      id: '/_authenticated/_wallet/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedWalletAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedWalletAccountsRoute
    }
    '/_authenticated/_wallet/accounts/$accountId': {
      id: '/_authenticated/_wallet/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedWalletAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedWalletAccountsRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedWalletAccountsRouteChildren {
  AuthenticatedWalletAccountsAccountIdRoute: typeof AuthenticatedWalletAccountsAccountIdRoute
  AuthenticatedWalletAccountsIndexRoute: typeof AuthenticatedWalletAccountsIndexRoute
}

const AuthenticatedWalletAccountsRouteChildren: AuthenticatedWalletAccountsRouteChildren =
  {
    AuthenticatedWalletAccountsAccountIdRoute:
      AuthenticatedWalletAccountsAccountIdRoute,
    AuthenticatedWalletAccountsIndexRoute:
      AuthenticatedWalletAccountsIndexRoute,
  }

const AuthenticatedWalletAccountsRouteWithChildren =
  AuthenticatedWalletAccountsRoute._addFileChildren(
    AuthenticatedWalletAccountsRouteChildren,
  )

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletAccountsRoute: typeof AuthenticatedWalletAccountsRouteWithChildren
  AuthenticatedWalletDashboardRoute: typeof AuthenticatedWalletDashboardRoute
  AuthenticatedWalletTransactionsRoute: typeof AuthenticatedWalletTransactionsRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletAccountsRoute:
    AuthenticatedWalletAccountsRouteWithChildren,
  AuthenticatedWalletDashboardRoute: AuthenticatedWalletDashboardRoute,
  AuthenticatedWalletTransactionsRoute: AuthenticatedWalletTransactionsRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
